### ISSUE TITLE
Thread 1.2.0 Core Implementation

### ISSUE THREAD

**Issue by jwhui** [openthread/openthread#4327]
This issue tracks Thread 1.2.0 core feature implementation.

- [x] Thread 1.2 feature flag (#4325)
- [x] Parent Selection rules (#4423)
- [x] Enhanced Keep Alive (#4325)
- [x] Enhanced Frame Pending (#4334)
- [x] Ack Frame Generator Functions (#4884)
- [x] Move Transmit AES-CCM* processing to sub-mac (#4919)
- [x] Link Metrics
  - [x] Single Probe (#5481)
  - [x] Forward Tracking Series (#5608)
  - [x] Enhanced ACK Probing (#5780)
- [x] Coordinated Sampled Listening (#4557)
- [x] Backbone Router service (#4430)
- [x] All Network Backbone Routers Multicast Address (#4755)
- [x] Domain Name (#4815)
- [x] Domain Unicast Address Registration
  - [x] Domain Prefix (#4793)
  - [x] All Domain Backbone Routers Multicast Address (#4795)
  - [x] Domain Unicast Address generation (#4854)
  - [x] Prioritize DUA in Address Registration TLV (#4862)
  - [x] Allow manual DUA IID configuration (#4900)
  - [x] Store DUA DAD counter in non-volatile (#4904)
  - [x] Register Domain Unicast Addresses (#5276)
- [x] Multicast Address Registration
  - [x] MED Multicast Registration to Parent (#4837)
  - [x] Register local multicast addresses (#5248)
  - [x] Register child multicast addresses (#5236)
  - [x] Backbone Router multicast listeners table (#5292)
  - [x] Add multicast forwarding for MLR Listeners (https://github.com/openthread/ot-br-posix/pull/532)
  - [x] Add Commissioner API to register Multicast Listeners (#5346)
  - [x] Configure MLR.req response status (#5350)
  - [x] Send BMLR.ntf on Backbone link (#5388)
- [x] Backbone TMF Agent (#5471)

**Comment by zhifeng1756** [comment]
Does Openthread supports Commissioning and configuration via BLE as stated in Thread [v1.2](https://www.threadgroup.org/Portals/0/documents/support/ThreadInCommercialWhitePaper_2542_1.pdf)? If not yet, any plan?

Thanks,

**Comment by jwhui** [comment]
> Does Openthread supports Commissioning and configuration via BLE as stated in Thread [v1.2](https://www.threadgroup.org/Portals/0/documents/support/ThreadInCommercialWhitePaper_2542_1.pdf)? If not yet, any plan?

@zhifeng1756 , OpenThread does not currently support Bluetooth Extensions. Currently, we do not have a roadmap to support this feature.

**Comment by khaled34** [comment]
What will be the release date for openthread 1.2 ?
