### ISSUE TITLE
List of PRs for SRP and DNS-SD feature

### ISSUE THREAD

**Issue by abtink** [openthread/openthread#6106]
Using this issue here to list and track all the PRs related to SRP and DNS-SD feature in OT repo (specifically the order we want to merge and/or they way they depend on one another). This is mainly to help us quickly access the PRs.

SRP related PRs:
- [x] [srp] common utils #6048
- [x] [net] SRP client implementation #6038
- [x] [net] initial implementation of the SRP server #5986
- [x] [tests] add CI tests for the SRP server & client #6074
- [x] [ncp] add support for SRP client in NCP and spinel #6062
- [x] [advertising-proxy] initial implementation of the Advertising Proxy https://github.com/openthread/ot-br-posix/pull/666
- [x] [srp] add CI tests for SRP server & Advertising Proxy #6131
- [x] [net-data] add 'NetworkData::Service' module #6130
- [x] [srp-client] new methods to get server address, set callback #6134
- [x] [srp-client] adding auto-start feature #6140
- [x] [srp-client] adding service pool module #6257

DNS-SD related PRs:

- [x] [dns] fix dns failed to append names of length 255 #6088
- [x] [dns-name] require message offset to point to DNS header #6101
- [x] [dns-header] new methods to compare label/name from message #6078
- [x] [dns-header] helper methods to parse/find/read record(s) in a message #6097
- [x] [dns-client] service discovery (DNS-SD) support and enhancements #6116
- [x] [dns-sd] DNS-SD server implementation #6103
- [x] [dns-server] handle multiple questions #6155
- [x] [dns-client] add 'QueryConfig' and default config #6172

Other related PRs (utility functions and/or small fixes):
- [x] [dns] add helper methods to append/parse DNS names #5922
- [x] [crypto] add ECDSA (P-256 curve) key-gen, signing, and verification #5954
- [x] [crypto] add new flavors of 'Update()' for SHA-256 and HMAC computation #6002
- [x] [ecdsa] relax/fix the assert check on MPI encoded size #6051
- [x] [dns-headers] fix typos, rename some methods #6059
- [x] [dns-client] use 'Header::SetRandomMessageId()' to set query message ID #6061
- [x] [logging] add logging region DNS #6069
- [x] [dns-client] remove QuestionAaaa class #6075
- [x] [net] get parsed TXT entry from SRP server #6113
- [x] [dns] match DNS name with specific domain #6114
- [x] [dns-name] allow 'Dns::Name' to be given as string or from message #6117
- [x] [dns-header] new helper method to find i-th record matching name and type #6124
- [x] [dns-header] add common TXT record entry parsing API #6157
- [x] [dns] update DNS/SRP client documentation to use doxygen lists #6169
- [x] [dns] fix and simplify OPT record reuse of TTL field #6187
- [x] [dns] rename to 'dns_types.hpp' #6193

**Comment by abtink** [comment]
Closing this.
